version: "3"

dotenv:
  - .env

tasks:
  dev:
    desc: "Run bot in development mode with polling"
    cmds:
      - go run ./cmd/opencode-bot

  build:
    desc: "Build static binary"
    cmds:
      - go build -o opencode-bot -ldflags "-s -w" ./cmd/opencode-bot

  tidy:
    desc: "Tidy Go dependencies"
    cmds:
      - go mod tidy

  docker:build:
    desc: "Build Docker image"
    cmds:
      - docker build -t opencode-bot:latest .

  docker:run:
    desc: "Run Docker container"
    cmds:
      - docker run -d --name opencode-bot -p 8080:8080 --env-file .env opencode-bot:latest

  test:
    desc: "Run unit tests"
    cmds:
      - go test ./...

  test:verbose:
    desc: "Run unit tests (verbose)"
    cmds:
      - go test -v ./...

  lint:
    desc: "Run golangci-lint using repo config"
    cmds:
      - |
        if command -v golangci-lint >/dev/null 2>&1; then
          golangci-lint run --config .golangci.yml ./...
        else
          "$(go env GOPATH)/bin/golangci-lint" run --config .golangci.yml ./...
        fi

  lint:install:
    desc: "Install pinned golangci-lint binary"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8

  ci:
    desc: "Run local checks aligned with CI workflow"
    cmds:
      - go build -v ./...
      - go test -v ./...
      - task lint
      - task coverage:check

  coverage:
    desc: "Run tests and produce coverage profile"
    cmds:
      - go test -covermode=count -coverprofile=coverage.out ./internal/... ./pkg/...

  coverage:check:
    desc: "Fail if coverage is below 50%"
    cmds:
      - go test -covermode=count -coverprofile=coverage.out ./internal/... ./pkg/...
      - go run ./cmd/coveragecheck -file coverage.out -min 50

  coverage:html:
    desc: "Generate HTML coverage report"
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
